<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/03/29 05:13:50
sfConfig::add(array(
  'app_tarjetascredito_falsa' => 'off',
  'app_tarjetascredito_visa' => 'on',
  'app_tarjetascredito_americanexpress' => 'on',
));
