<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/04/01 02:49:54
sfConfig::add(array(
  'app_tarjetascredito_falsa' => 'on',
  'app_tarjetascredito_visa' => 'on',
  'app_tarjetascredito_americanexpress' => 'on',
));
