<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/03/29 05:14:29

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=prueba1',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
