<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/03/29 05:14:29
sfConfig::add(array(
  'app_tarjetascredito_falsa' => 'ohhh motherfucker yeah!!',
  'app_tarjetascredito_visa' => 'on',
  'app_tarjetascredito_americanexpress' => 'on',
));
