<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/03/04 03:04:59
sfConfig::add(array(
  'app_tarjetascredito_falsa' => 'ohhh motherfucker yeah!!',
  'app_tarjetascredito_visa' => 'on',
  'app_tarjetascredito_americanexpress' => 'on',
));
