<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/04/01 03:12:15
$this->security = array (
  'setusuario' => 
  array (
    'is_secure' => false,
  ),
  'getusuario' => 
  array (
    'is_secure' => true,
  ),
  'destroyuser' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
